/**
 * DS_TEMPLATE_V1 — Pine Script v6 generator
 *
 * Generates a DS_LEVELS_BTC indicator from a dom_levels_last.json payload.
 * The generated script encodes snapshot values as var constants so they
 * persist across bars without re-computation.
 */

// ─── Types ────────────────────────────────────────────────────────────────────

export type StalenessTier = "fresh" | "aging" | "stale";

export interface DomLevel {
  price: number;
  size: number;
  cumulative: number;
}

export interface DomSummary {
  bid_total_size: number;
  ask_total_size: number;
  bid_ask_ratio: number;
  spread: number;
  spread_bps: number;
  mid_price: number;
  imbalance: number;
}

export interface DomMetadata {
  levels_count: number;
  update_latency_ms: number;
  source: string;
  version: string;
  staleness_tier: string;
  data_age_ms: number;
}

export interface DomPayload {
  timestamp: number;
  timestamp_iso: string;
  symbol: string;
  exchange: string;
  levels: {
    bid: DomLevel[];
    ask: DomLevel[];
  };
  summary: DomSummary;
  metadata: DomMetadata;
}

export interface StalenessResult {
  tier: StalenessTier;
  age_ms: number;
  age_s: number;
}

// ─── Staleness ────────────────────────────────────────────────────────────────

const FRESH_THRESHOLD_MS = 60_000;    //  <60s
const AGING_THRESHOLD_MS = 300_000;   // 60s – 5min

export function computeStaleness(payloadTimestamp: number): StalenessResult {
  const age_ms = Date.now() - payloadTimestamp;
  const age_s = Math.round(age_ms / 1000);
  const tier: StalenessTier =
    age_ms < FRESH_THRESHOLD_MS
      ? "fresh"
      : age_ms < AGING_THRESHOLD_MS
        ? "aging"
        : "stale";
  return { tier, age_ms, age_s };
}

// ─── Generator ────────────────────────────────────────────────────────────────

export function generateDsTemplateV1(
  payload: DomPayload,
  staleness: StalenessResult,
  cycleId: string
): string {
  const { summary, levels } = payload;
  const { tier, age_ms } = staleness;

  const staleness_code = tier === "fresh" ? 0 : tier === "aging" ? 1 : 2;

  // Take top 5 per side; pad with zeros if fewer levels available
  const bids = padLevels(levels.bid.slice(0, 5), 5);
  const asks = padLevels(levels.ask.slice(0, 5), 5);

  // Null-safe summary extraction (partial payloads during fetcher startup)
  const imbalance   = summary.imbalance        ?? 0;
  const bid_total   = summary.bid_total_size   ?? 0;
  const ask_total   = summary.ask_total_size   ?? 0;
  const bid_ask_r   = summary.bid_ask_ratio    ?? 0;
  const mid_price   = summary.mid_price        ?? 0;
  const spread_bps  = summary.spread_bps       ?? 0;

  const f = (n: number | undefined, decimals = 4): string =>
    (n ?? 0).toFixed(decimals);

  const bidConsts = bids
    .map(
      (b, i) =>
        `var float B${i}_P = ${f(b.price, 2)}  // bid[${i}] price\n` +
        `var float B${i}_S = ${f(b.size, 4)}  // bid[${i}] size`
    )
    .join("\n");

  const askConsts = asks
    .map(
      (a, i) =>
        `var float A${i}_P = ${f(a.price, 2)}  // ask[${i}] price\n` +
        `var float A${i}_S = ${f(a.size, 4)}  // ask[${i}] size`
    )
    .join("\n");

  const bidPlots = bids
    .map(
      (_, i) =>
        `plot(B${i}_P, "b${i}_price", display=display.data_window)\n` +
        `plot(B${i}_S, "b${i}_size",  display=display.data_window)`
    )
    .join("\n");

  const askPlots = asks
    .map(
      (_, i) =>
        `plot(A${i}_P, "a${i}_price", display=display.data_window)\n` +
        `plot(A${i}_S, "a${i}_size",  display=display.data_window)`
    )
    .join("\n");

  const staleness_label =
    tier === "stale" ? "STALE" : tier === "aging" ? "AGING" : "FRESH";

  return `//@version=6
// DS_LEVELS_BTC — Auto-generated by DS_INJECT_ORCHESTRATOR
// Cycle    : ${cycleId}
// Data     : ${payload.timestamp_iso ?? new Date(payload.timestamp).toISOString()}
// Staleness: ${tier} (${Math.round(age_ms / 1000)}s old)
// DO NOT EDIT MANUALLY — overwritten every 15 min
indicator("DS_LEVELS_BTC", shorttitle="DS_BTC", overlay=false, max_labels_count=5)

// ── Summary snapshot ─────────────────────────────────────────────────────────
var float IMBALANCE   = ${f(imbalance, 6)}
var float BID_TOTAL   = ${f(bid_total, 4)}
var float ASK_TOTAL   = ${f(ask_total, 4)}
var float BID_ASK_R   = ${f(bid_ask_r, 4)}
var float MID_PRICE   = ${f(mid_price, 2)}
var float SPREAD_BPS  = ${f(spread_bps, 4)}
var float STALE_CODE  = ${staleness_code.toFixed(1)}  // 0=fresh 1=aging 2=stale

// ── Top 5 bid levels ─────────────────────────────────────────────────────────
${bidConsts}

// ── Top 5 ask levels ─────────────────────────────────────────────────────────
${askConsts}

// ── Primary plots ────────────────────────────────────────────────────────────
plot(IMBALANCE,  "imbalance",   color=color.new(color.blue, 0),   linewidth=2)
plot(BID_TOTAL,  "bid_total",   color=color.new(color.green, 0))
plot(ASK_TOTAL,  "ask_total",   color=color.new(color.red, 0))
plot(BID_ASK_R,  "bid_ask_r",   color=color.new(color.orange, 0), display=display.data_window)
plot(MID_PRICE,  "mid_price",   color=color.new(color.gray, 0),   display=display.data_window)
plot(SPREAD_BPS, "spread_bps",  color=color.new(color.gray, 0),   display=display.data_window)
plot(STALE_CODE, "stale_code",  color=color.new(color.white, 0),  display=display.data_window)

// ── Level plots (data window only) ───────────────────────────────────────────
${bidPlots}
${askPlots}

// ── Staleness overlay ────────────────────────────────────────────────────────
bgcolor(STALE_CODE == 2.0 ? color.new(color.red, 70) :
        STALE_CODE == 1.0 ? color.new(color.yellow, 80) : na,
        title="staleness_bg")

// ── Info label (last bar only) ───────────────────────────────────────────────
var label _lbl = na
if barstate.islast
    label.delete(_lbl)
    _lbl := label.new(bar_index, IMBALANCE,
          text  = "DS_BTC | imb=" + str.tostring(IMBALANCE, "#.####") +
                  " | bal=" + str.tostring(BID_ASK_R, "#.##") +
                  " | " + (STALE_CODE == 2.0 ? "STALE" : STALE_CODE == 1.0 ? "AGING" : "FRESH"),
          style = label.style_label_left,
          color = STALE_CODE == 2.0 ? color.red :
                  STALE_CODE == 1.0 ? color.yellow : color.green,
          textcolor = color.white,
          size  = size.small)
`;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function padLevels(levels: DomLevel[], count: number): DomLevel[] {
  const padded = [...levels];
  while (padded.length < count) {
    padded.push({ price: 0, size: 0, cumulative: 0 });
  }
  return padded;
}
